-- Script para limpiar completamente la base de datos y empezar desde cero
BEGIN
    EXECUTE IMMEDIATE 'DELETE FROM TRANSPORTE_PASAJEROS';
    EXECUTE IMMEDIATE 'DELETE FROM ENTREGA_COMIDA';
    EXECUTE IMMEDIATE 'DELETE FROM TRANSPORTE_MERCANCIA';
    EXECUTE IMMEDIATE 'DELETE FROM RESEÑA';
    EXECUTE IMMEDIATE 'DELETE FROM DESTINOS_SERVICIO';
    EXECUTE IMMEDIATE 'DELETE FROM SERVICIO';
    EXECUTE IMMEDIATE 'DELETE FROM DISPONIBILIDAD';
    EXECUTE IMMEDIATE 'DELETE FROM TARJETA_CREDITO';
    EXECUTE IMMEDIATE 'DELETE FROM VEHICULO';
    EXECUTE IMMEDIATE 'DELETE FROM PUNTO_TRAYECTO';
    EXECUTE IMMEDIATE 'DELETE FROM USUARIO';
    EXECUTE IMMEDIATE 'DELETE FROM CIUDAD';
    DBMS_OUTPUT.PUT_LINE('Todos los datos eliminados');
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM user_sequences WHERE sequence_name = 'SERVICIO_SEQ';
    IF v_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SERVICIO_SEQ';
    END IF;
    
    SELECT COUNT(*) INTO v_exists FROM user_triggers WHERE trigger_name = 'SERVICIO_BI';
    IF v_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP TRIGGER SERVICIO_BI';
    END IF;
END;
/

COMMIT;
